const PDFDocument = require('pdfkit');

/**
 * Generate a PDF invoice as a Buffer.
 *
 * @param {Object} params
 * @param {string} params.instanceName - Company/property manager name
 * @param {string} params.tenantName
 * @param {string} params.unitNumber
 * @param {string} params.buildingName
 * @param {string} params.period - e.g. "2026-07"
 * @param {number} params.rent
 * @param {number} params.serviceCharge
 * @param {number} params.waterUsage
 * @param {number} params.waterCharge
 * @param {number} params.totalAmount
 * @param {string} params.currency - e.g. "KES"
 * @param {string} params.invoiceId
 * @param {string} params.createdAt - ISO timestamp
 * @param {string} [params.dueDate]
 * @returns {Promise<Buffer>} PDF file content
 */
function generateInvoicePdf(params) {
  const {
    instanceName = 'Property Manager',
    tenantName,
    unitNumber,
    buildingName,
    period,
    rent = 0,
    serviceCharge = 0,
    waterUsage = 0,
    waterCharge = 0,
    totalAmount = 0,
    currency = 'KES',
    invoiceId,
    createdAt,
    dueDate,
  } = params;

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'A4', margin: 50 });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - 100; // minus margins

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('INVOICE', { align: 'center' });
    doc.moveDown(0.5);

    // Company info
    doc.fontSize(12).font('Helvetica-Bold').text(instanceName);
    doc.fontSize(9).font('Helvetica').text('Powered by TenantBilling');
    doc.moveDown(1);

    // Invoice details line
    doc.fontSize(9).font('Helvetica');
    const invoiceDate = createdAt ? new Date(createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '';
    doc.text(`Invoice #: ${invoiceId || '-'}`, { continued: true });
    doc.text(`    Date: ${invoiceDate}`, { align: 'right' });
    if (dueDate) {
      doc.text(`Due Date: ${dueDate}`);
    }
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.8);

    // Bill To section
    doc.fontSize(10).font('Helvetica-Bold').text('BILL TO:');
    doc.fontSize(10).font('Helvetica');
    doc.text(tenantName);
    if (unitNumber) doc.text(`Unit: ${unitNumber}`);
    if (buildingName) doc.text(`Building: ${buildingName}`);
    doc.moveDown(1);

    doc.fontSize(10).font('Helvetica-Bold').text(`Billing Period: ${formatPeriod(period)}`);
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.5);

    // Table Header
    const tableTop = doc.y;
    const col1 = 50;
    const col2 = 350;
    const colWidth1 = 280;

    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('Description', col1, tableTop, { width: colWidth1 });
    doc.text('Amount', col2, tableTop, { width: 150, align: 'right' });
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#eeeeee');
    doc.moveDown(0.5);

    // Line items
    doc.font('Helvetica').fontSize(10);
    const items = [];

    if (rent > 0) items.push({ desc: 'Monthly Rent', amount: rent });
    if (serviceCharge > 0) items.push({ desc: 'Service Charge', amount: serviceCharge });
    if (waterCharge > 0) items.push({ desc: `Water Charge (${waterUsage} units)`, amount: waterCharge });

    for (const item of items) {
      const y = doc.y;
      doc.text(item.desc, col1, y, { width: colWidth1 });
      doc.text(`${currency} ${item.amount.toLocaleString()}`, col2, y, { width: 150, align: 'right' });
      doc.moveDown(0.7);
    }

    // Total line
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.5);

    doc.fontSize(12).font('Helvetica-Bold');
    const totalY = doc.y;
    doc.text('TOTAL DUE', col1, totalY, { width: colWidth1 });
    doc.text(`${currency} ${totalAmount.toLocaleString()}`, col2, totalY, { width: 150, align: 'right' });
    doc.moveDown(2);

    // Footer
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.8);
    doc.fontSize(8).font('Helvetica').fillColor('#666666');
    doc.text('Payment can be made via mobile money. You will receive a payment prompt on your phone.', { align: 'center' });
    doc.moveDown(0.3);
    doc.text('For queries, please contact your property manager.', { align: 'center' });
    doc.moveDown(0.5);
    doc.text('Generated by TenantBilling - www.tenantbilling.africa', { align: 'center' });

    doc.end();
  });
}

/**
 * Generate a PDF payment receipt as a Buffer.
 */
function generateReceiptPdf(params) {
  const {
    instanceName = 'Property Manager',
    tenantName,
    unitNumber,
    buildingName,
    period,
    amount,
    currency = 'KES',
    transactionId,
    paidAt,
    invoiceId,
  } = params;

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'A4', margin: 50 });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - 100;

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('PAYMENT RECEIPT', { align: 'center' });
    doc.moveDown(0.5);

    // Company info
    doc.fontSize(12).font('Helvetica-Bold').text(instanceName);
    doc.fontSize(9).font('Helvetica').text('Powered by TenantBilling');
    doc.moveDown(1);

    // Receipt details
    const formattedDate = paidAt ? new Date(paidAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : '';
    doc.fontSize(9).font('Helvetica');
    doc.text(`Receipt Date: ${formattedDate}`);
    doc.text(`Transaction ID: ${transactionId || '-'}`);
    if (invoiceId) doc.text(`Invoice Reference: ${invoiceId}`);
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.8);

    // Received From
    doc.fontSize(10).font('Helvetica-Bold').text('RECEIVED FROM:');
    doc.fontSize(10).font('Helvetica');
    doc.text(tenantName);
    if (unitNumber) doc.text(`Unit: ${unitNumber}`);
    if (buildingName) doc.text(`Building: ${buildingName}`);
    doc.moveDown(1);

    // Payment details
    doc.fontSize(10).font('Helvetica-Bold').text(`Period: ${formatPeriod(period)}`);
    doc.moveDown(1);

    // Amount box
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.8);

    doc.fontSize(14).font('Helvetica-Bold');
    doc.text(`Amount Received: ${currency} ${amount.toLocaleString()}`, { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(11).font('Helvetica').fillColor('#228B22');
    doc.text('PAID IN FULL', { align: 'center' });
    doc.fillColor('#000000');
    doc.moveDown(2);

    // Footer
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).stroke('#cccccc');
    doc.moveDown(0.8);
    doc.fontSize(8).font('Helvetica').fillColor('#666666');
    doc.text('Thank you for your payment.', { align: 'center' });
    doc.moveDown(0.3);
    doc.text('Generated by TenantBilling - www.tenantbilling.africa', { align: 'center' });

    doc.end();
  });
}

function formatPeriod(period) {
  if (!period) return '-';
  const [year, month] = period.split('-');
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[parseInt(month, 10) - 1] || month} ${year}`;
}

module.exports = { generateInvoicePdf, generateReceiptPdf };
